spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

  application:
    name: smoothtune

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG

storage:
  location: uploads/songs

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${REGION}

aws:
  bucket:
    name: ${BUCKET_NAME}

jwt:
  key:
    secret: ${JWT_KEY}
    ttl: ${EXPIRATION_TIME}