spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

  application:
    name: smoothtune

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG


storage:
  location: uploads/songs

cloud:
  aws:
    credentials:
      access-key: LLAVEDEACCESODEPRUEBA
      secret-key: llavesecretadepruebaparas3
    region:
      static: us-east-1

aws:
  bucket:
    name: bucketName

jwt:
  key:
    secret: "nh9FZbi/XQer89C4e14U5A8lGn+n0TgFKsjB0xd092U="
    ttl: 3600000