spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smoothtune
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop   # opciones: none, validate, update, create, create-drop
    show-sql: true       # muestra las consultas en consola
    properties:
      hibernate:
        format_sql: true # formatea las consultas para mayor legibilidad



  application:
    name: smoothtune

logging:
  level:
    org.hibernate.SQL: DEBUG

storage:
  location: uploads/songs



#storage:
#  location: ${STORAGE_PATH:${user.home}/smoothtune/uploads/songs}